---

- name: "cert: Create {{ poudriere_ssl_dir }}"
  file:
    state: directory
    path: "{{ poudriere_ssl_dir }}"
    owner: "{{ poudriere_owner }}"
    group: "{{ poudriere_group }}"
    mode: 0755
  tags: poudriere_ssl_dirs

- name: "cert: Create {{ poudriere_ssl_dir }}/crt"
  file:
    state: directory
    path: "{{ poudriere_ssl_dir }}/crt"
    owner: "{{ poudriere_owner }}"
    group: "{{ poudriere_group }}"
    mode: "{{ poudriere_ssl_dir_mode }}"
  tags: poudriere_ssl_dirs

- name: "cert: Create {{ poudriere_ssl_dir }}/csr"
  file:
    state: directory
    path: "{{ poudriere_ssl_dir }}/csr"
    owner: "{{ poudriere_owner }}"
    group: "{{ poudriere_group }}"
    mode: "{{ poudriere_ssl_dir_mode }}"
  tags: poudriere_ssl_dirs

- name: "cert: Create {{ poudriere_ssl_dir }}/public"
  file:
    state: directory
    path: "{{ poudriere_ssl_dir }}/public"
    owner: "{{ poudriere_owner }}"
    group: "{{ poudriere_group }}"
    mode: "{{ poudriere_ssl_dir_mode }}"
  tags: poudriere_ssl_dirs

- name: "cert: Create {{ poudriere_ssl_dir }}/private"
  file:
    state: directory
    path: "{{ poudriere_ssl_dir }}/private"
    owner: "{{ poudriere_owner }}"
    group: "{{ poudriere_group }}"
    mode: "{{ poudriere_ssl_private_dir_mode }}"
  tags: poudriere_ssl_dirs

- name: "cert: Generate an OpenSSL private key (default 4096 bits, RSA)"
  when: poudriere_cert_create and not ansible_check_mode
  openssl_privatekey:
    path: "{{ poudriere_conf['PKG_REPO_SIGNING_KEY'] }}"
    owner: "{{ poudriere_owner }}"
    group: "{{ poudriere_group }}"
    mode: "{{ poudriere_ssl_private_key_mode }}"
  tags: poudriere_crt

- name: "cert: Generate an OpenSSL public key"
  when: poudriere_cert_create and not ansible_check_mode
  openssl_publickey:
    path: "{{ poudriere_pubkey_path }}"
    privatekey_path: "{{ poudriere_conf['PKG_REPO_SIGNING_KEY'] }}"
  tags: poudriere_pubkey

- name: "cert: Register contents of {{ poudriere_pubkey_path }}"
  when: poudriere_cert_create and not ansible_check_mode
  command: "cat {{ poudriere_pubkey_path }}"
  register: pubkey
  tags: poudriere_pubkey

- name: "cert: Set a fact containing the OpenSSL public key"
  when: poudriere_cert_create and not ansible_check_mode
  set_fact:
    poudriere_pubkey: "{{ pubkey.stdout }}"
    cacheable: yes
  tags: poudriere_pubkey

- name: "cert: Generate an OpenSSL Certificate Signing Request"
  when: poudriere_cert_create and not ansible_check_mode
  openssl_csr:
    path: "{{ poudriere_ssl_dir }}/csr/poudriere.csr"
    privatekey_path: "{{ poudriere_conf['PKG_REPO_SIGNING_KEY'] }}"
    common_name: "{{ poudriere_cert_CN }}"
  tags: poudriere_crt

- name: "cert: Generate a Self Signed OpenSSL certificate"
  when: poudriere_cert_create and not ansible_check_mode
  openssl_certificate:
    path: "{{ poudriere_cert_path }}"
    privatekey_path: "{{ poudriere_conf['PKG_REPO_SIGNING_KEY'] }}"
    csr_path: "{{ poudriere_ssl_dir }}/csr/poudriere.csr"
    provider: selfsigned
  tags: poudriere_crt

# EOF
...
