---

- name: "Conf: configure {poudriere_conf_file}"
  ansible.builtin.template:
    src: poudriere.conf.j2
    dest: "{{ poudriere_conf_file }}"
    owner: "{{ poudriere_owner }}"
    group: "{{ poudriere_group }}"
    mode: "{{ poudriere_mode }}"
    backup: "{{ poudriere_backup_conf | bool }}"

- name: "Conf: create {poudriere_conf['DISTFILES_CACHE']}"
  ansible.builtin.file:
    state: directory
    path: "{{ poudriere_conf['DISTFILES_CACHE'] }}"
    owner: "{{ poudriere_owner }}"
    group: "{{ poudriere_group }}"
    mode: "{{ poudriere_mode_dir }}"

- name: "Conf: create directories for pkglists, as required"
  ansible.builtin.file:
    state: directory
    path: "{{ item.name | dirname }}"
    owner: "{{ poudriere_owner }}"
    group: "{{ poudriere_group }}"
    mode: "{{ poudriere_mode_dir }}"
  loop: "{{ poudriere_pkglists }}"

- name: "Conf: create lists of packages"
  ansible.builtin.template:
    src: poudriere.pkglist.j2
    dest: "{{ item.name }}"
    owner: "{{ poudriere_owner }}"
    group: "{{ poudriere_group }}"
    mode: "{{ poudriere_mode }}"
    backup: "{{ poudriere_backup_conf | bool }}"
  loop: "{{ poudriere_pkglists }}"

...
