---

- name: "Conf: configure {poudriere_conf_file}"
  ansible.builtin.template:
    src: "poudriere.conf.j2"
    dest: "{{ poudriere_conf_file }}"
    owner: "{{ poudriere_owner }}"
    group: "{{ poudriere_group }}"
    mode: "{{ poudriere_mode }}"
    backup: "{{ poudriere_backup_conf | bool }}"

- name: "Conf: create {poudriere_conf['DISTFILES_CACHE']}"
  ansible.builtin.file:
    state: directory
    path: "{{ poudriere_conf['DISTFILES_CACHE'] }}"
    owner: "{{ poudriere_owner }}"
    group: "{{ poudriere_group }}"
    mode: "{{ poudriere_mode_dir }}"

- name: "Conf: create list of packages"
  ansible.builtin.include_tasks: pkglist.yml
  loop: "{{ poudriere_pkg_arch }}"
  loop_control:
    loop_var: pkg_arch

# EOF
...
