---
- name: "Conf: configure {poudriere_conf_file}"
  ansible.builtin.lineinfile:
    state: present
    line: "{{ item.key }}={{ item.value | quote }}"
    regexp: ^#?{{ item.key }}=
    path: "{{ poudriere_conf_file }}"
    owner: "{{ poudriere_owner }}"
    group: "{{ poudriere_group }}"
    mode: "{{ poudriere_mode }}"
    backup: "{{ poudriere_backup_conf | bool }}"
  loop: "{{ poudriere_conf | dict2items }}"

- name: "Conf: create {poudriere_conf['DISTFILES_CACHE']}"
  ansible.builtin.file:
    state: directory
    path: "{{ poudriere_conf['DISTFILES_CACHE'] }}"
    owner: "{{ poudriere_owner }}"
    group: "{{ poudriere_group }}"
    mode: "{{ poudriere_mode_dir }}"

- name: "Conf: create directories for pkglists, as required"
  ansible.builtin.file:
    state: directory
    path: "{{ poudriere_conf_dir }}/{{ item | dirname }}"
    owner: "{{ poudriere_owner }}"
    group: "{{ poudriere_group }}"
    mode: "{{ poudriere_mode_dir }}"
  loop: "{{ poudriere_pkglist_files }}"

- name: "Conf: install package list files"
  ansible.builtin.copy:
    src: "{{ inventory_hostname }}/{{ item | basename }}"
    dest: "{{ poudriere_conf_dir }}/{{ item }}"
    owner: "{{ poudriere_owner }}"
    group: "{{ poudriere_group }}"
    mode: "{{ poudriere_mode }}"
    backup: "{{ poudriere_backup_conf | bool }}"
  loop: "{{ poudriere_pkglist_files }}"
