---

- name: "Poudriere Debug"
  vars:
    msg: |
         ansible_architecture [ {{ ansible_architecture }} ]
         ansible_os_family [ {{ ansible_os_family }} ]
         ansible_distribution [ {{ ansible_distribution }} ]
         ansible_distribution_major_version [ {{ ansible_distribution_major_version }} ]
         ansible_distribution_version [ {{ ansible_distribution_version }} ]
         ansible_distribution_release [ {{ ansible_distribution_release }} ]

         poudriere_packages [
         {{ poudriere_packages | to_nice_yaml }} ]
         poudriere_packages_cert [
         {{ poudriere_packages_cert | to_nice_yaml }} ]
         poudriere_backup_conf [ {{ poudriere_backup_conf|bool }} ]
         poudriere_owner [ {{ poudriere_owner }} ]
         poudriere_group [ {{ poudriere_group }} ]
         poudriere_mode [ {{ poudriere_mode }} ]
         poudriere_mode_dir [ {{ poudriere_mode_dir }} ]
         poudriere_ssl_dir [ {{ poudriere_ssl_dir }} ]
         poudriere_ssl_dir_mode [ {{ poudriere_ssl_dir_mode }} ]
         poudriere_ssl_private_dir_mode [ {{ poudriere_ssl_private_dir_mode }} ]
         poudriere_ssl_private_key_mode [ {{ poudriere_ssl_private_key_mode }} ]
         poudriere_cert_create [ {{ poudriere_cert_create }} ]
         poudriere_cert_cn [ {{ poudriere_cert_cn }} ]
         poudriere_cert_path [ {{ poudriere_cert_path }} ]
         poudriere_conf_file [ {{ poudriere_conf_file }} ]
         poudriere_conf_dir [ {{ poudriere_conf_dir }} ]
         poudriere_conf [ {{ poudriere_conf| to_nice_yaml }} ]
         poudriere_make_conf [ {{ poudriere_make_conf | to_nice_yaml }} ]
         poudriere_pkglist_dir [ {{ poudriere_pkglist_dir }} ]
         apache_version [ {{ apache_version }} ]
         apache_php_version [ {{ apache_php_version }} ]
         bsd_php_version [ {{ bsd_php_version }} ]
         bsd_dhcp_version [ {{ bsd_dhcp_version }} ]
         bsd_bind_version [ {{ bsd_bind_version }} ]
         bsd_mysql_version [ {{ bsd_mysql_version }} ]
         bsd_python_version [ {{ bsd_python_version }} ]
         poudriere_pkg_arch [
         {{ poudriere_pkg_arch | to_yaml }} ]
  debug:
    msg: "{{ msg.split('\n') }}"

# EOF
...
