---
# tasks freebsd-poudriere

- name: Packages
  ansible.builtin.import_tasks: packages.yml
  tags: poudriere_packages

- name: Certificate
  ansible.builtin.import_tasks: cert.yml
  when: "'PKG_REPO_SIGNING_KEY' in poudriere_conf"
  tags: poudriere_cert

- name: Configuration
  ansible.builtin.import_tasks: conf.yml
  tags: poudriere_config

- name: Make
  ansible.builtin.import_tasks: make.yml
  tags: poudriere_make

- name: UFS
  ansible.builtin.import_tasks: ufs.yml
  tags: poudriere_ufs

- name: CCache
  ansible.builtin.import_tasks: ccache.yml
  when: "'CCACHE_DIR' in poudriere_conf"
  tags: poudriere_ccache

- name: Ports
  ansible.builtin.import_tasks: ports.yml
  tags: poudriere_ports

- name: Jails
  ansible.builtin.import_tasks: jails.yml
  tags: poudriere_jails

- name: ZFS
  ansible.builtin.import_tasks: zfs.yml
  tags: poudriere_zfs
