---
# tasks freebsd-poudriere

- import_tasks: debug.yml
  when: poudriere_debug
  tags: [poudriere_debug, always]

- import_tasks: packages.yml
  tags: poudriere_packages

- import_tasks: cert.yml
  tags: poudriere_cert

- import_tasks: conf.yml
  tags: poudriere_config

- import_tasks: make.yml
  tags: poudriere_make

- import_tasks: zfs.yml
  when: poudriere_use_zfs
  tags: poudriere_zfs

- import_tasks: ports.yml
  tags: poudriere_ports

- import_tasks: jails.yml
  tags: poudriere_jails

# EOF
...
