---

- name: "Packages: Install poudriere packages"
  community.general.packaging.os.pkgng:
    name: "{{ poudriere_packages }}"

- name: "Packages: Install packages to create certificate"
  when: poudriere_cert_create
  community.general.packaging.os.pkgng:
    name: "{{ poudriere_packages_cert }}"

# EOF
...
