---

- name: "packages: Install poudriere packages"
  pkgng:
    name: "{{ poudriere_packages }}"

- name: "packages: Install packages to create certificate"
  when: poudriere_cert_create
  pkgng:
    name: "{{ poudriere_packages_cert }}"

# EOF
...
