---

- name: Find existing ports trees
  shell: 'poudriere ports -l -q | cut -f 1 -w 2>/dev/null'
  args:
    executable: /bin/sh
  ignore_errors: true
  changed_when: false
  register: ports_trees

- debug:
    var: ports_trees
  
- name: Set up ports tree(s) for poudriere
  when: item.name not in ports_trees.stdout_lines
  command: >
    poudriere ports -c  -p {{ item.name }} -m {{ item.method }}
    {% if 'mountpoint' in item %}-M {{ item.mountpoint }}{% endif %}
    {% if 'branch' in item %}-N {{ item.branch }}{% endif %}
    {% if 'fs' in item %}-f {{ item.fs }}{% endif %}
  loop: '{{ poudriere_ports }}'

...
