---
- name: "ZFS: update properties in the ZFSes used by poudriere"
  when: poudriere_use_zfs | bool
  community.general.zfs:
    name: "{{ item.key }}"
    state: present
    extra_zfs_properties: "{{ item.value }}"
  loop: "{{ poudriere_zfs | dict2items }}"
  tags: poudriere_zfs
