---

- name: Create the ZFSes used by poudriere
  zfs:
    name: '{{ item.key }}'
    state: present
    extra_zfs_properties:
      '{{ item.value }}'
  loop: '{{ poudriere_zfs|dict2items }}'

...


